"""Core package for Rookie Quest: Ringmaster."""

from .game import BookingSlot, WeeklyShow
from .universe import create_custom_brand, generate_universe
from .weekly import WeeklyLoop
from .models import MatchOutcome, Segment, Wrestler
from .modes import GameMode, ModeRules, rules_for_mode
from .savegame import SaveGame, create_save, load_from_file, save_to_file
from .show_assignment import AssignmentReport, ShowAssignment, ShowAssignmentEngine
from .sim import SimulationEngine

__all__ = [
    "Wrestler",
    "GameMode",
    "ModeRules",
    "rules_for_mode",
    "Segment",
    "MatchOutcome",
    "SimulationEngine",
    "BookingSlot",
    "WeeklyShow",
    "WeeklyLoop",
    "Storyline",
    "StorylineEngine",
    "TalentProfile",
    "TalentPool",
    "TalentTrainer",
    "StaffMember",
    "RosterNeed",
    "StaffSynergyReport",
    "StaffOffice",
    "SteamReadiness",
    "SteamLaunchPlanner",
    "MoraleState",
    "MoraleEngine",
    "PromotionProfile",
    "CareerRuntimeService",
    "RuntimeWeekResult",
    "MainRoster",
    "DevelopmentRoster",
    "GraduationResult",
    "RosterPipeline",
    "PromotionBalanceReport",
    "PromotionPlanner",
    "ProductionInventory",
    "ProductionPlanner",
    "EntranceDemand",
    "EntranceAssignment",
    "EntranceBudgetReport",
    "EntranceBudgetManager",
    "PPVEvent",
    "PPVScheduler",
    "generate_universe",
    "create_custom_brand",
    "CampaignEngine",
    "CampaignSnapshot",
    "WrestlerCareerState",
    "BookingOpportunity",
    "LifestyleChoiceResult",
    "ContractType",
    "WrestlerCareerRPG",
    "BookingBoard",
    "BookingSegment",
    "FictionalBrandSeed",
    "fictional_brand_name",
    "fictional_wrestler_name",
    "ShowAssignment",
    "AssignmentReport",
    "ShowAssignmentEngine",
    "SaveGame",
    "create_save",
    "save_to_file",
    "load_from_file",
]
