import ringmaster


def test_public_package_exports_are_available() -> None:
    expected_exports = [
        "Wrestler",
        "Segment",
        "MatchOutcome",
        "SimulationEngine",
        "BookingSlot",
        "WeeklyShow",
        "WeeklyLoop",
        "WeeklyReport",
        "Storyline",
        "StorylineEngine",
        "MoraleState",
        "MoraleEngine",
        "PromotionProfile",
        "PromotionBalanceReport",
        "PromotionPlanner",
        "ProductionInventory",
        "ProductionPlanner",
        "EntranceDemand",
        "EntranceAssignment",
        "EntranceBudgetReport",
        "EntranceBudgetManager",
        "PPVEvent",
        "PPVScheduler",
        "generate_universe",
        "create_custom_brand",
        "CampaignEngine",
        "CampaignSnapshot",
        "FictionalBrandSeed",
        "fictional_brand_name",
        "fictional_wrestler_name",
        "SaveGame",
        "create_save",
        "save_to_file",
        "load_from_file",
        "GameMode",
        "ModeRules",
        "rules_for_mode",
        "BookingBoard",
        "BookingSegment",
        "TalentProfile",
        "TalentPool",
        "TalentTrainer",
        "StaffMember",
        "RosterNeed",
        "StaffSynergyReport",
        "StaffOffice",
        "SteamReadiness",
        "SteamLaunchPlanner",
        "CareerRuntimeService",
        "RuntimeWeekResult",
        "MainRoster",
        "DevelopmentRoster",
        "GraduationResult",
        "RosterPipeline",
        "WrestlerCareerState",
        "BookingOpportunity",
        "LifestyleChoiceResult",
        "ContractType",
        "WrestlerCareerRPG",
        "ShowAssignment",
        "AssignmentReport",
        "ShowAssignmentEngine",
    ]

    missing = [name for name in expected_exports if not hasattr(ringmaster, name)]
    assert missing == []
